version: "3.7"

services:
  proxy:
    build: .
    #image: decentralize/caching-proxy:pr-5
    image: ptagliolato/caching-proxy:v1
    environment:
      UPSTREAM: https://deims.org
      MAX_SIZE: 1g
      ALLOWED_ORIGIN: https://deims.org
      PROXY_CACHE_VALID: 60m
    ports:
      - 8082:80/tcp
